"""PostgreSQL support for persistent Community Cloud storage."""
from contextlib import contextmanager


class Row(dict):
    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


def row_factory(cursor):
    names = [column.name for column in cursor.description] if cursor.description else []
    return lambda values: Row(zip(names, values))


class Connection:
    def __init__(self, connection):
        self.raw = connection

    def execute(self, sql, params=None):
        # Store statements use only positional placeholders, never SQL literals
        # containing question marks. Values are still bound by the driver.
        return self.raw.execute(sql.replace("?", "%s"), params)


def schema_sql(sqlite_schema):
    return (sqlite_schema.replace("PRAGMA user_version=1;", "")
            .replace("id INTEGER PRIMARY KEY,", "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,")
            .replace("run_id INTEGER", "run_id BIGINT")
            .replace("rule_id INTEGER", "rule_id BIGINT")
            .replace("job_id INTEGER", "job_id BIGINT")
            .replace("heartbeat REAL", "heartbeat DOUBLE PRECISION"))


class Postgres:
    def __init__(self, settings, sqlite_schema):
        from psycopg_pool import ConnectionPool
        from .db_connection import DeadlineConnection

        allowed = {"host", "port", "dbname", "user", "password", "sslmode", "sslrootcert"}
        if not {"host", "dbname", "user", "password"}.issubset(settings):
            raise ValueError("В Secrets необходимы database.host, dbname, user, password")
        kwargs = {key:value for key,value in settings.items() if key in allowed}
        kwargs.setdefault("port", 5432)
        kwargs.setdefault("sslmode", "require")
        if kwargs["sslmode"] not in {"require", "verify-ca", "verify-full"}:
            raise ValueError("Облачная база требует SSL")
        from .db_settings import connection_settings
        kwargs = connection_settings(kwargs)
        self.settings = dict(kwargs)
        kwargs.update(connect_timeout=10, prepare_threshold=None, row_factory=row_factory)
        self.pool = ConnectionPool(connection_class=DeadlineConnection, kwargs=kwargs, min_size=1, max_size=4, max_idle=60, timeout=15, open=True)
        try:
            self.pool.wait(timeout=15)
            with self.connect() as c:
                self.lock(c)
                c.execute("CREATE SCHEMA IF NOT EXISTS price_monitor")
                c.execute("CREATE TABLE IF NOT EXISTS schema_version (id INTEGER PRIMARY KEY, version INTEGER NOT NULL)")
                version = c.execute("SELECT version FROM schema_version WHERE id=1").fetchone()
                if version and version[0] != 1:
                    raise RuntimeError("Версия облачной базы не поддерживается")
                for statement in schema_sql(sqlite_schema).split(";"):
                    if statement.strip():
                        c.execute(statement)
                c.execute("ALTER TABLE observations ADD COLUMN IF NOT EXISTS details_json TEXT NOT NULL DEFAULT '{}'")
                c.execute("ALTER TABLE external_sources ADD COLUMN IF NOT EXISTS protocol INTEGER NOT NULL DEFAULT 1")
                c.execute("INSERT INTO schema_version VALUES(1,1) ON CONFLICT(id) DO NOTHING")
                from .sensoren_payload import SCHEMA as TRANSFER_SCHEMA
                for statement in TRANSFER_SCHEMA:
                    c.execute(statement)
        except Exception:
            self.pool.close()
            raise

    @contextmanager
    def connect(self):
        with self.pool.connection() as raw:
            # A dedicated schema keeps tables out of Supabase's public Data API.
            raw.execute("SET LOCAL search_path TO price_monitor")
            raw.execute("SET LOCAL statement_timeout TO '20s'")
            raw.execute("SET LOCAL lock_timeout TO '10s'")
            yield Connection(raw)

    @staticmethod
    def lock(c):
        # Transaction-scoped, works with a pooler and serializes queue/lease writes.
        c.execute("SELECT pg_advisory_xact_lock(6743928101)")

    def close(self):
        self.pool.close()
