from pathlib import Path
import threading
import time
import unittest
from unittest.mock import MagicMock, patch

from streamlit.testing.v1 import AppTest
import streamlit as st

from price_monitor.cloud import EmbeddedWorker, CancellationProbe
from price_monitor.models import Rule
from price_monitor.postgres import Connection, Row, row_factory, schema_sql, Postgres
from price_monitor.storage import Store, SCHEMA
from price_monitor.worker import Worker
from support import TestDirectory


class PostgresContractTests(unittest.TestCase):
    def test_sql_schema_is_postgres_and_epoch_keeps_precision(self):
        sql = schema_sql(SCHEMA)
        self.assertNotIn('PRAGMA', sql)
        self.assertEqual(sql.count('GENERATED BY DEFAULT AS IDENTITY'), 4)
        self.assertIn('heartbeat DOUBLE PRECISION', sql)
        self.assertIn('run_id BIGINT', sql)
        self.assertIn('one_active_run', sql)

    def test_values_remain_bound_and_rows_support_keys_and_positions(self):
        raw = MagicMock()
        value = "text'; DROP TABLE rules;--"
        Connection(raw).execute('SELECT article FROM rules WHERE article=?', (value,))
        raw.execute.assert_called_once_with('SELECT article FROM rules WHERE article=%s', (value,))
        row = Row([('id',3),('name','test')])
        self.assertEqual(row[0],3)
        self.assertEqual(row['name'],'test')
        self.assertEqual(dict(row),{'id':3,'name':'test'})

    def test_pool_initialization_schema_lock_and_transaction_scope(self):
        # These tests exercise the driver contract; they do not claim to connect
        # to a real Supabase project, which requires the owner's credentials.
        from psycopg_pool import ConnectionPool
        pool = MagicMock(spec=ConnectionPool)
        raw = pool.connection.return_value.__enter__.return_value
        raw.execute.return_value.fetchone.return_value = None
        with patch('psycopg_pool.ConnectionPool',return_value=pool) as factory:
            pg = Postgres({'host':'pool.example','dbname':'postgres','user':'postgres.example','password':'fake-secret'},SCHEMA)
            kwargs = factory.call_args.kwargs['kwargs']
            self.assertEqual(kwargs['sslmode'],'require')
            self.assertIsNone(kwargs['prepare_threshold'])
            self.assertLessEqual(factory.call_args.kwargs['max_size'],8)
            queries = [c.args[0] for c in raw.execute.call_args_list]
            self.assertIn('SET LOCAL search_path TO price_monitor',queries)
            self.assertIn('SELECT pg_advisory_xact_lock(6743928101)',queries)
            self.assertIn('CREATE SCHEMA IF NOT EXISTS price_monitor',queries)
            pg.close();pool.close.assert_called_once()

    def test_cloud_rejects_missing_settings_and_unencrypted_database(self):
        with self.assertRaises(ValueError):Postgres({},SCHEMA)
        with self.assertRaises(ValueError):Postgres({'host':'h','dbname':'d','user':'u','password':'p','sslmode':'disable'},SCHEMA)


class CloudRuntimeTests(unittest.TestCase):
    def test_background_worker_completes_saved_queue_and_exits(self):
        with TestDirectory() as folder:
            store = Store(Path(folder)/'cloud.db')
            rule = Rule('sensoren','ifm','SI5000','https://sensoren.ru/product/si5000/')
            run = store.enqueue([rule])
            class Client:
                def __init__(self,*args,**kwargs):pass
                def fetch(self,url):return url,404,''
                def close(self):pass
            runner = EmbeddedWorker(store,worker_factory=lambda db:Worker(db,Client))
            try:
                deadline=time.monotonic()+10
                while store.runs()[0]['state']!='completed' and time.monotonic()<deadline:
                    time.sleep(.05)
                self.assertEqual(store.results(run)[0]['status'],'not_found')
                self.assertEqual(store.runs()[0]['state'],'completed')
            finally:
                runner.close()
            self.assertFalse(runner.thread.is_alive())

    def test_cancellation_probe_limits_db_queries_and_stop_is_immediate(self):
        stop=threading.Event();check=MagicMock(return_value=False)
        probe=CancellationProbe(check,stop,ttl=60)
        for _ in range(100):self.assertFalse(probe())
        check.assert_called_once()
        stop.set();self.assertTrue(probe())

    def test_cloud_entrypoint_uses_shared_services_without_login(self):
        with TestDirectory() as folder:
            store=Store(Path(folder)/'app.db')
            runtime=MagicMock()
            st.cache_resource.clear()
            with patch('streamlit.secrets',{'database':{'host':'fake-db'}}),patch('price_monitor.storage.Store',return_value=store) as init,patch('price_monitor.cloud.EmbeddedWorker',return_value=runtime) as start:
                app=AppTest.from_file(str(Path(__file__).parents[1]/'streamlit_app.py'),default_timeout=30).run()
                self.assertFalse(app.exception)
                self.assertEqual(init.call_args.kwargs,{'postgres':{'host':'fake-db'}})
                app.run()
                start.assert_called_once()
                self.assertTrue(any('Общий доступ' in item.value for item in app.sidebar.caption))
                self.assertFalse(app.text_input)
            st.cache_resource.clear()

    def test_cloud_database_error_does_not_expose_credentials_or_fall_back(self):
        st.cache_resource.clear()
        with patch('streamlit.secrets',{'database':{'password':'sensitive-value'}}),patch('price_monitor.storage.Store',side_effect=RuntimeError('sensitive-value')) as init:
            app=AppTest.from_file(str(Path(__file__).parents[1]/'streamlit_app.py'),default_timeout=30).run()
            self.assertFalse(app.exception)
            self.assertTrue(app.error)
            self.assertNotIn('sensitive-value',app.error[0].value)
            init.assert_called_once()
        st.cache_resource.clear()


if __name__=='__main__':unittest.main()
