[theme]
base = "light"
primaryColor = "#176B87"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F6FA"
textColor = "#172B3A"
font = "sans serif"

[server]
headless = true
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
