[theme]
primaryColor = "#7A1F2B"
backgroundColor = "#F4F6F8"
secondaryBackgroundColor = "#F3ECEE"
textColor = "#32262B"
font = "sans serif"

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
